"""
This module contains a function to shuffle and replace elements in an array
with random numbers using a subprocess.
"""

import subprocess


def random_array(arr):
    """
    Replaces each element in the input array with a random number
    generated by calling the `shuf` command.

    Args:
        arr (list): The list of numbers to shuffle.

    Returns:
        list: The modified list with random numbers.
    """
    for i, _ in enumerate(arr):  # Using enumerate instead of range(len(arr))
        shuffled_num = subprocess.run(
            ["shuf", "-i1-20", "-n1"], capture_output=True, check=True)  # Added `check=True`
        arr[i] = int(shuffled_num.stdout)
    return arr
